name: backend-workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test-and-deploy:
    runs-on: ubuntu-latest

    services:
        mysql:
          image: mysql:8
          env:
              MYSQL_DATABASE: user_sql
              MYSQL_ROOT_PASSWORD: Sakura1204
          ports:
            - 3306:3306

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22.1'

    - name: Wait for MySQL to be ready
      run: |
        for i in {1..30}; do
          if mysqladmin ping -h 127.0.0.1 --silent; then
            echo "MySQL is up and running!"
            break
          fi
          echo "Waiting for MySQL to be ready... ($i/30)"
          sleep 2
        done

    - name: Create database
      run: |
        mysql -h 127.0.0.1 -uroot -pSakura1204 -e "CREATE DATABASE IF NOT EXISTS user_sql;"

    - name: Build
      run: go build .

    - name: Run tests
      run: cd service && go test