name: backend-workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test-and-deploy:
    runs-on: ubuntu-latest

    services:
        mysql:
          image: mysql:8
          env:
              MYSQL_DATABASE: user_sql
              MYSQL_HOST: 127.0.0.1
              MYSQL_USER: root
              MYSQL_PASSWORD: Sakura1204
              MYSQL_ROOT_PASSWORD: Sakura1204
          ports:
            - 3306:3306

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22.1'

    - name: Build
      run: go build .

    - name: Run tests
      run: cd service && go test